# -*- coding: utf-8 -*-
"""Latex_walker_aggeregation.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1dRJ8GWV4lsz6vcprjl3sTagl-3e_nvGF
"""

directory_name = "/content/drive/MyDrive/thesis"
latext_directory_name = "/content/drive/MyDrive/latex_papers/2001.06776"

main_latex_file_path = "/content/drive/MyDrive/latex_papers/2001.06776/Krishnamurthy20.tex"

def latex_file_read_remove_comment(file_path):
  latex_text_list = open(file_path).readlines()
  latex_file_wo_comments = []
    # removal of comments in the latex files
  for line in latex_text_list:
    if not line.startswith("%"):
      latex_file_wo_comments.append(line)
  latex_text_wo_comments = "".join(latex_file_wo_comments)
  return latex_text_wo_comments

main_latex_text_wo_comments = latex_file_read_remove_comment(main_latex_file_path)

import re
def latex_extract_input_files(latex_text_cleaned):
    input_file_names = re.findall(r'\\input{(.*?)}', latex_text_cleaned, re.S)
    return input_file_names

imported_latex_file_names= latex_extract_input_files(main_latex_text_wo_comments)

imported_latex_file_names

latext_directory_name

import os
input_files_path_list = []
input_file_path_content_dir = {}
for latex_input_files in imported_latex_file_names:
    file_path = os.path.join(latext_directory_name, latex_input_files) + ".tex"
    input_files_path_list.append(file_path)
    latex_text_wo_comments= latex_file_read_remove_comment(file_path)
    input_file_command= "\input{" + latex_input_files +  "}"  
    input_file_path_content_dir[input_file_command]  = latex_text_wo_comments

import os
def create_file_path_content_dir(imported_latex_file_names):
  input_files_path_list = []
  input_file_path_content_dir = {}
  for latex_input_files in imported_latex_file_names:
      file_path = os.path.join(latext_directory_name, latex_input_files) + ".tex"
      input_files_path_list.append(file_path)
      latex_text_wo_comments= latex_file_read_remove_comment(file_path)
      input_file_command= "\input{" + latex_input_files +  "}"  
      input_file_path_content_dir[input_file_command]  = latex_text_wo_comments
  return input_file_path_content_dir

input_file_path_content_dir

main_latex_file_content_new = main_latex_text_wo_comments
for import_file in input_file_path_content_dir:
  print(import_file)
  main_latex_file_content_new = main_latex_file_content_new.replace(import_file, input_file_path_content_dir[import_file] )

# main_latex_file_content_new

# print(main_latex_file_content_new)